package com.fengwenyi.demo.mybatis.user.model;

import java.util.Date;

public class UserAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.id
     *
     * @mbg.generated Thu May 17 12:06:47 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.account
     *
     * @mbg.generated Thu May 17 12:06:47 CST 2018
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.password
     *
     * @mbg.generated Thu May 17 12:06:47 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.user_id
     *
     * @mbg.generated Thu May 17 12:06:47 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.time_create
     *
     * @mbg.generated Thu May 17 12:06:47 CST 2018
     */
    private Date timeCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.time_hander
     *
     * @mbg.generated Thu May 17 12:06:47 CST 2018
     */
    private Date timeHander;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.id
     *
     * @return the value of user_auth.id
     *
     * @mbg.generated Thu May 17 12:06:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.id
     *
     * @param id the value for user_auth.id
     *
     * @mbg.generated Thu May 17 12:06:47 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.account
     *
     * @return the value of user_auth.account
     *
     * @mbg.generated Thu May 17 12:06:47 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.account
     *
     * @param account the value for user_auth.account
     *
     * @mbg.generated Thu May 17 12:06:47 CST 2018
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.password
     *
     * @return the value of user_auth.password
     *
     * @mbg.generated Thu May 17 12:06:47 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.password
     *
     * @param password the value for user_auth.password
     *
     * @mbg.generated Thu May 17 12:06:47 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.user_id
     *
     * @return the value of user_auth.user_id
     *
     * @mbg.generated Thu May 17 12:06:47 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.user_id
     *
     * @param userId the value for user_auth.user_id
     *
     * @mbg.generated Thu May 17 12:06:47 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.time_create
     *
     * @return the value of user_auth.time_create
     *
     * @mbg.generated Thu May 17 12:06:47 CST 2018
     */
    public Date getTimeCreate() {
        return timeCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.time_create
     *
     * @param timeCreate the value for user_auth.time_create
     *
     * @mbg.generated Thu May 17 12:06:47 CST 2018
     */
    public void setTimeCreate(Date timeCreate) {
        this.timeCreate = timeCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.time_hander
     *
     * @return the value of user_auth.time_hander
     *
     * @mbg.generated Thu May 17 12:06:47 CST 2018
     */
    public Date getTimeHander() {
        return timeHander;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.time_hander
     *
     * @param timeHander the value for user_auth.time_hander
     *
     * @mbg.generated Thu May 17 12:06:47 CST 2018
     */
    public void setTimeHander(Date timeHander) {
        this.timeHander = timeHander;
    }
}